apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawlee
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: wait-for-postgres
              image: busybox:1.32
              command: ["sh", "-c", "until nc -z -v app-crawlee-postgres 5432; do sleep 1; done"]
          containers:
          - name: crawlee-app
            image: "230410870031.dkr.ecr.eu-west-3.amazonaws.com/crawlee-app:$IMAGE_VERSION"
            env:
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: crawlee-app-config
                  key: AWS_S3_BUCKET_NAME
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: crawlee-app-config
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef: 
                  name: crawlee-app-secret
                  key: CRAWLEE_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: crawlee-app-secret
                  key: CRAWLEE_SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: crawlee-app-secret
                  key: DATABASE_URL
          restartPolicy: OnFailure
