# not working 100% yet
apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-aws-ecr-login> # aws ecr get-login-password --region eu-west-3 | tr -d '\n'
