apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crawlee-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-delete-sc # This is the storage class name that we created in IaC
  resources:
    requests:
      storage: 30Gi